// <auto-generated />
using System;
using CourseEnrollment.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseEnrollment.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CourseEnrollment.Data.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Credit")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6534),
                            Credit = 20,
                            Name = "Front End",
                            UpdatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6535)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6536),
                            Credit = 30,
                            Name = "Back End",
                            UpdatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6537)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6538),
                            Credit = 45,
                            Name = "Full Stack",
                            UpdatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6539)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6540),
                            Credit = 25,
                            Name = "Mobile Programming",
                            UpdatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6540)
                        });
                });

            modelBuilder.Entity("CourseEnrollment.Data.Entities.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            CreatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6690),
                            StudentId = 1,
                            UpdatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6690)
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            CreatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6691),
                            StudentId = 1,
                            UpdatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6691)
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            CreatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6692),
                            StudentId = 1,
                            UpdatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6692)
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            CreatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6693),
                            StudentId = 2,
                            UpdatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6693)
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 4,
                            CreatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6694),
                            StudentId = 2,
                            UpdatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6694)
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 1,
                            CreatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6695),
                            StudentId = 3,
                            UpdatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6695)
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 4,
                            CreatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6695),
                            StudentId = 3,
                            UpdatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6696)
                        });
                });

            modelBuilder.Entity("CourseEnrollment.Data.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6645),
                            Firstname = "Sadig",
                            Lastname = "Aliyev",
                            StudentId = "STD001",
                            UpdatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6645)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6647),
                            Firstname = "Rovshane",
                            Lastname = "Rzayeva",
                            StudentId = "STD002",
                            UpdatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6647)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6648),
                            Firstname = "Aysel",
                            Lastname = "Hasanli",
                            StudentId = "STD003",
                            UpdatedAt = new DateTime(2023, 5, 8, 12, 6, 13, 424, DateTimeKind.Local).AddTicks(6648)
                        });
                });

            modelBuilder.Entity("CourseEnrollment.Data.Entities.Enrollment", b =>
                {
                    b.HasOne("CourseEnrollment.Data.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseEnrollment.Data.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
